
preload = /home/alex/Pictures/Wallpapers/wallpaper.png
preload = /home/alex/Pictures/Wallpapers/wallpaper-left.png
preload = /home/alex/Pictures/Wallpapers/wallpaper-right.png

# home setup
wallpaper = HDMI-A-1, /home/alex/Pictures/Wallpapers/wallpaper-left.png
wallpaper = HDMI-A-2, /home/alex/Pictures/Wallpapers/wallpaper-right.png

# office setup
wallpaper = eDP-1, /home/alex/Pictures/Wallpapers/wallpaper-left.png
wallpaper = DP-1, /home/alex/Pictures/Wallpapers/wallpaper-right.png
